name: run main.py
on:
  schedule:
    - cron: "*/2 * * * *" # run every 2 min
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"
          cache: pip
      - name: Install python packages
        run: pip install -r requirements.txt
      - name: Run main.py
        run: python main.py
